### ISSUE TITLE
Full paths in /tmp do not behave as expected with par2 create with 0.7.0

### ISSUE THREAD

**Issue by ilovezfs** [Parchive/par2cmdline#93] opened 2017-04-18 07:41 UTC
Testing on macOS (10.10, 10.11, and 10.12).
See https://bot.brew.sh/job/Homebrew%20Core%20Pull%20Requests/65/

Without full paths all is well:
```
bash-3.2$ echo "file contents" > some-file
bash-3.2$ par2 create some-file

Block size: 4
Source file count: 1
Source block count: 4
Redundancy: 5%
Recovery block count: 1
Recovery file count: 1

Opening: some-file
Computing Reed Solomon matrix.
Constructing: done.
Wrote 4 bytes to diskets
Writing recovery packets
Writing verification packets
Done
bash-3.2$ echo "corrupted contents" > some-file
bash-3.2$ par2 repair some-file
Loading "some-file.par2".
Loaded 4 new packets
Loading "some-file.vol0+1.par2".
Loaded 1 new packets including 1 recovery blocks
Loading "some-file.par2".
No new packets found

There are 1 recoverable files and 0 other files.
The block size used was 4 bytes.
There are a total of 4 data blocks.
The total size of the data files is 14 bytes.

Verifying source files:

Target: "some-file" - damaged. Found 3 of 4 data blocks.

Scanning extra files:


Repair is required.
1 file(s) exist but are damaged.
You have 3 out of 4 data blocks available.
You have 1 recovery blocks available.
Repair is possible.
1 recovery blocks will be used to repair.

Computing Reed Solomon matrix.
Constructing: done.
Solving: done.

Wrote 14 bytes to disk

Verifying repaired files:

Target: "some-file" - found.

Repair complete.
bash-3.2$ cat some-file
file contents
```

Passing a full path in /tmp to `par2 create`, all is not well:
```
bash-3.2$ rm -rf some-file*
bash-3.2$ echo "file contents" > some-file
bash-3.2$ ls
some-file
bash-3.2$ par2 create `pwd`/some-file

Block size: 4
Source file count: 1
Source block count: 4
Redundancy: 5%
Recovery block count: 1
Recovery file count: 1

Opening: e
Computing Reed Solomon matrix.
Constructing: done.
Wrote 4 bytes to diskets
Writing recovery packets
Writing verification packets
Done
bash-3.2$ echo "corrupted contents" > some-file
bash-3.2$ par2 repair some-file
Loading "some-file.par2".
Loaded 4 new packets
Loading "some-file.vol0+1.par2".
Loaded 1 new packets including 1 recovery blocks
Loading "some-file.par2".
No new packets found

There are 1 recoverable files and 0 other files.
The block size used was 4 bytes.
There are a total of 4 data blocks.
The total size of the data files is 14 bytes.

Verifying source files:

Target: "e" - missing.

Scanning extra files:


Repair is required.
1 file(s) are missing.
You have 0 out of 4 data blocks available.
You have 1 recovery blocks available.
Repair is not possible.
You need 3 more recovery blocks to be able to repair.
bash-3.2$ pwd
/tmp/partest
bash-3.2$ 
```

**Comment by BlackIkeEagle** [comment] 2017-04-18 12:04
I have added some tests, one with your exact behaviour and another where everything is in a subfolder and the error you have is not reproducable

there was another issue triggered by this but not the one described above

**Comment by BlackIkeEagle** [comment] 2017-04-18 12:07
No, but this would be very bizarre if its only showing on macOS

**Comment by ilovezfs** [comment] 2017-04-18 12:07
Indeed, but that's the point!
```
iMac-TMP:~ joe$ ls -l /|grep tmp
lrwxr-xr-x@  1 root  wheel    11 Dec 25  2015 tmp -> private/tmp
iMac-TMP:~ joe$
```

**Comment by BlackIkeEagle** [comment] 2017-04-18 12:08
So you say the same scenario as you describe only occurs in /tmp

**Comment by ilovezfs** [comment] 2017-04-18 12:08
correct :)
(see issue title)

**Comment by BlackIkeEagle** [comment] 2017-04-18 12:09
Ok I see How I might be able to test it since Its not related to /tmp, I rather think its related to the symlink

**Comment by ilovezfs** [comment] 2017-04-18 12:09
Yup, that would be my guess!

**Comment by BlackIkeEagle** [comment] 2017-04-18 12:10
Thanks I'll look into it further

**Comment by ilovezfs** [comment] 2017-04-18 12:10
thanks :)

**Comment by BlackIkeEagle** [comment] 2017-04-19 19:23
@ilovezfs could you verify that the issue is now fixed, test27 should cover your case and its passing now

**Comment by ilovezfs** [comment] 2017-04-19 19:27
@BlackIkeEagle yes fixed!
```
==> /usr/local/Cellar/par2/HEAD-d8615e5/bin/par2 create /tmp/par2-test-20170419-39684-1d1rwn5/some-file

Block size: 4
Source file count: 1
Source block count: 4
Redundancy: 5%
Recovery block count: 1
Recovery file count: 1

Opening: some-file
Computing Reed Solomon matrix.
Constructing: done.
Wrote 4 bytes to diskets
Writing recovery packets
Writing verification packets
Done
==> /usr/local/Cellar/par2/HEAD-d8615e5/bin/par2 repair /tmp/par2-test-20170419-39684-1d1rwn5/some-file
iMac-TMP:~ joe$ 
```

**Comment by BlackIkeEagle** [comment] 2017-04-19 20:23
thanks for testing @ilovezfs

**Closed by BlackIkeEagle** 2017-04-19 20:23 UTC

**Comment by ilovezfs** [comment] 2017-04-19 20:43
You're welcome!

**Comment by BlackIkeEagle** [comment] 2017-05-20 06:58
0.7.1 is released, so the previous style of testing should work again in homebrew

**Comment by ilovezfs** [comment] 2017-05-20 07:39
@BlackIkeEagle thanks https://github.com/Homebrew/homebrew-core/pull/13756.
