### ISSUE TITLE
 Support for french accents

### ISSUE THREAD

**Issue by phibryzo** [Parchive/par2cmdline#59] opened 2015-09-11 22:51 UTC
Hi, I'm Phibryzo.
I'm french and I use par2commandline for my personal data. Thank for your job.

Under Windows (cmd), I can create par2 file with accents in their name. However, in verify or repair function, the testing file not support french accents. Repair is not possible.
I used the "-N" argument for solve this problem, but can you adapt support accents in the par2.exe ?

Thank you

**Comment by BlackIkeEagle** [comment] 2015-09-12 14:44
I'm going to close thisone since its a duplicate of #39

**Closed by BlackIkeEagle** 2015-09-12 14:44 UTC
